name: gcd-test-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Permission Setting
        run: chmod +x gcd_test.sh
      - name: Test Run
        run: ./gcd_test.sh
